#theme: jekyll-theme-slate

title: Demo Level
description: Game Demo Level

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true 
  
mermaid:
  custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
